# config/train_cnn.yaml

# --- 基本設定 ---
data_path: "/home/ktr/f1tenth_ws/E2ETENTH-2025-JP/python/supervised_train_kei/datasets/625/625_slow_kei"
ckpt_path: "./out_ckpts"

## model パラメータ
## TinyLidarNet, TinyLidarLstmNet, TinyLidarConvLstmNet
## TinyLidarActionNet, TinyLidarActionLstmNet, TinyLidarActionConvLstmNet
## TinyLidarConvTransformerNet

model_name: "TinyLidarNet" 

# --- モデルパラメータ ---
input_dim: 1081
output_dim: 2
sequence_length: 1
range_max: 30.0

# --- 学習パラメータ ---
lr: 0.0005
num_epochs: 100
early_stop_epochs: 10

# --- データローダパラメータ ---
batch_size: 8 
random_ratio: 1.0  # バッチの XX% をランダムサンプルにする
flip_prob: 0.5
noise_std: 0.01
num_workers: 10      # ランダムローダ用のnum_workers
hydra:
  run:
    dir: ./outputs/train_cnn/${now:%Y-%m-%d}/${now:%H-%M-%S}

