/**:
  ros__parameters:
    # フィルタの種類: "average", "median", "none" から選択
    filter_type: "average"
    # 移動平均/中央値フィルタのウィンドウサイズ
    window_size: 5
    # スケール/クリップフィルタを有効にするか
    use_scale_filter: true
    speed_scale_ratio: 1.0
    steer_scale_ratio: 1.0