# config/train_cnn.yaml

# --- 基本設定 ---
data_path: "./datasets/"
ckpt_path: "./ckpts"


# --- モデルパラメータ ---
input_dim: 1081
output_dim: 2
sequence_length: 10
range_max: 30.0

# --- 学習パラメータ ---
lr: 0.0001
num_epochs: 100
early_stop_epochs: 10

# --- データローダパラメータ ---
batch_size: 8 
random_ratio: 0.5   # バッチの XX% をランダムサンプルにする
flip_prob: 0.5
noise_std: 0.01
num_workers: 10      # ランダムローダ用のnum_workers
hydra:
  run:
    dir: ./outputs/train_cnn/${now:%Y-%m-%d}/${now:%H-%M-%S}

