/**:
  ros__parameters:
## TinyLidarNet 
## TinyLidarLstmNet, TinyLidarConvLstmNet
## TinyLidarActionLstmNet, TinyLidarActionConvLstmNet

    model_name: TinyLidarNet
    model_path: .pt
    max_range: 30.0
    input_dim: 1081
    output_dim: 2